{
    "groups":{
        "/list":[
            "catalog",
            "api",
            "docs",
            "api-docs",
            "/test/health"
        ],
        "/bit-bucket-pr":[
            "onboarding",
            "routing-rules"
        ],
        "/security":[
            "prometheus"
        ],
        "/resource-management":[
            "kubernetes/workload"
        ]
    }
}
